pair2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("reviews.urls")),
]

reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path('', views.index, name="index"),
    path('reviews/', views.reviews, name="home"),
    path('reviews/create/', views.create, name="create"),
    path('reviews/<int:pk>', views.detail, name='detail'),
    path('reviews/<int:pk>/delete', views.delete, name='delete'),
    path('reviews/<int:pk>/update', views.update, name='update'),
    path('reviews/search', views.search, name="search"),
]

reviews/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.
class Review(models.Model):
        title = models.CharField(max_length=80)
        content = models.TextField()
        movie_name = models.CharField(max_length=80)
        grade = models.IntegerField(validators=[MinValueValidator(1),MaxValueValidator(5)])
        created_at = models.DateTimeField(auto_now_add=True)
        updated_at = models.DateTimeField(auto_now=True)

reviews/forms.py
from dataclasses import fields
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = '__all__'

reviews/views.py
import string
from types import NoneType
from django.shortcuts import render, redirect
from .models import Review
from .forms import ReviewForm

# Create your views here.
def index(request):
    return render(request, "reviews/index.html")

def reviews(request):
    reviews = Review.objects.all()
    context = {
        "reviews" : reviews,
    }
    return render(request, "reviews/reviews.html", context)

def create(request):
    if request.method == "POST":
        review_form = ReviewForm(request.POST)
        
        if review_form.is_valid():
            review_form.save()
            return redirect('reviews:home')

    else:
        review_form = ReviewForm()
    
    context = {
        "review_form" : review_form,
    }
    return render(request, "reviews/create.html", context)

def detail(request,pk):
    review = Review.objects.get(pk=pk)

    context = {
        'review' : review,
    }
    return render(request, 'reviews/detail.html', context)

def delete(request, pk):
    review = Review.objects.get(pk=pk)
    review.delete()
    return redirect('reviews:home')

def update(request, pk):
    review = Review.objects.get(pk=pk)
    if request.method == "POST":
        review_form = ReviewForm(request.POST, instance=review)
        
        if review_form.is_valid():
            review_form.save()
            return redirect('reviews:detail',review.pk)

    else:
        review_form = ReviewForm(instance=review)
    
    context = {
        "review_form" : review_form,
    }
    return render(request, "reviews/update.html", context)

def search(request):
    search = request.GET.get("search")
    reviews = Review.objects.filter(title__contains=search)

    if  len(search) == 0:
        reviews = []
        text = "검색어를 입력하세요."

    elif len(reviews) == 0:
        text = "검색 결과가 없습니다."
        
    else:
        print(reviews)
        text = ""
        
    context = {
        "reviews" : reviews,
        "text" : text,
    }
    return render(request, 'reviews/reviews.html', context)

reviews/templates/reviews/create.html
{% extends 'base.html' %}
{% block content %}
  <form class="mt-3" action="{% url 'reviews:create' %}" method="POST">
    {% csrf_token %}
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_form review_form %}
    <div class="d-flex flex-row-reverse m-3">
      <input type="submit" class="btn btn-outline-dark text-decoration-none m-3" value="글쓰기">
    </div>
  </form>
{% endblock %}

reviews/templates/reviews/detail.html
{% extends 'base.html' %}
{% block content %}

  <div class="card text-center mt-5">
    <div class="card-header">
      <div class="card m-3 p-3">
        제목 :
        {{ review.title }}</div>
    </div>
    <div class="card-body">
      <h5 class="card-title d-flex justify-content-around">
        <span>
          영화제목 :
          {{ review.movie_name }}
        </span>
        <span>평점 :
          {{ review.grade }}</span>
      </h5>
      <p class="card-text mt-5">{{ review.content }}</p>
    </div>
    <div class="card-footer text-muted">
      수정시간 |
      {{ review.updated_at }}
    </div>
  </div>
  <div class="d-flex flex-row-reverse m-3">
    <a href="{% url 'reviews:delete' review.pk %}" class="btn btn-danger mx-2">삭제</a>
    <a href="{% url 'reviews:update' review.pk %}" class="btn btn-outline-primary mx-2">수정</a>
  </div>

{% endblock %}

reviews/templates/reviews/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PopcornReview</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'reviews/css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
  </head>

  <body>
    <!-- 네브바 -->
    <nav class="navbar navbar-expand-lg nav-bg">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'reviews:index'%}">
          <img class='log-size' src='{% static 'reviews/images/log2.png' %}'></img>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="a me-4 fs-4 fw-bold" aria-current="page" href="{% url 'reviews:home'%}">Home</a>
            </li>
            <li class="nav-item">
              <a class="a me-4 fs-4 fw-bold" href="{% url 'reviews:create' %}">새 글 쓰기</a>
            </li>
          </ul>
          <!-- 검색창 -->
          <form class="d-flex" role="search" action="{% url 'reviews:search' %}">
            <input class="form-control me-2" type="search" placeholder="검색어를 입력해주세요." aria-label="Search" name="search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
    <div class="main">
      <h1 class="animate__animated animate__backOutRight animate__duration-2s" style="line-height: 40rem; font-weight: bold; font-size: 8rem; color: purple;">어서오세요.</h1>
    </div>
    <!-- 푸터 -->
    <footer class="upper_main py-3 bg-dark text-light text-center fixed-bottom fs-5">
      Copyright © 문상희, 안예지, 최준홍 2022-10-07
    </footer>

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>

</html>

reviews/templates/reviews/reviews.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <a href="{% url 'reviews:create' %}" class="fixed-top">
    <img class="pencil" src="{% static 'reviews/images/pencil.png' %}" alt="">
  </a>
  {% for review in reviews %}
    <div class="mt-5">
      <div class="card h-100">
        <div class="card-body">
          <h5 class="card-title">
            <a href="{% url 'reviews:detail' review.pk %}" class="text-decoration-none fw-bold b">
              {{ review.title }}
            </a>
          </h5>
          <div>
            <p class="card-text">
              {{ review.movie_name }}
            </p>
            <p class="card-text">{{ review.grade }}</p>
          </div>

        </div>
        <div class="card-footer">
          <small class="text-muted">{{ review.updated_at }}</small>
        </div>
      </div>
    </div>
  {% endfor %}
  <h1 class="mt-5 text-center">{{ text }}</h1>
{% endblock %}

reviews/templates/reviews/update.html
{% extends 'base.html' %}
{% block content %}
  <form class="mt-3" action="" method="POST">
    {% csrf_token %}
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_form review_form %}
    <div class="d-flex flex-row-reverse m-3">
      <input type="submit" class="btn btn-outline-success fw-bold text-decoration-none m-3" value="수정하기">
    </div>
  </form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PopcornReview</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'reviews/css/style.css' %}">
  </head>

  <body style="height:10000px;">
    <!-- 네브바 -->
    <nav class="navbar navbar-expand-lg nav-bg">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'reviews:index'%}">
          <img class='log-size' src='{% static 'reviews/images/log2.png' %}'></img>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="a me-4 fs-4 fw-bold" aria-current="page" href="{% url 'reviews:home'%}">Home</a>
            </li>
            <li class="nav-item">
              <a class="a me-4 fs-4 fw-bold" href="{% url 'reviews:create' %}">새 글 쓰기</a>
            </li>
          </ul>
          <!-- 검색창 -->
          <form class="d-flex" role="search" action="{% url 'reviews:search' %}">
            <input class="form-control me-2" type="search" placeholder="검색어를 입력해주세요." aria-label="Search" name="search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
    <div class="container position-relative" style="margin-bottom: 10rem;">
      {% block content %}{% endblock %}
    </div>

    <!-- 푸터 -->
    <footer class="upper_main py-3 bg-dark text-light text-center bottom-0 fs-5">
      Copyright © 문상희, 안예지, 최준홍 2022-10-07
    </footer>

    <!-- JavaScript Bundle with Popper -->
    <script src=" https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity=" sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin=" anonymous" =" anonymous" "=" anonymous" "=" anonymous" "" "></script>
  </body>

</html>